# Generated by Django 4.2.6 on 2023-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['-date_updated'], 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
